// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8_pkc-hDKVBv0EJk4EZKqh6ccsCo9HO4',
    appId: '1:886195487754:web:b8acd13b5379ce55c84bf3',
    messagingSenderId: '886195487754',
    projectId: 'nada-976f5',
    authDomain: 'nada-976f5.firebaseapp.com',
    storageBucket: 'nada-976f5.firebasestorage.app',
    measurementId: 'G-X9JCSRQ9M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_iQveMueIYv3QmwqEqEzfjYKFkPBqGY',
    appId: '1:886195487754:android:76353a704ab5fb64c84bf3',
    messagingSenderId: '886195487754',
    projectId: 'nada-976f5',
    storageBucket: 'nada-976f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6lsF7NUqtTKXK96kGG4-dIioupA9iSUk',
    appId: '1:886195487754:ios:5b7d93a546861a89c84bf3',
    messagingSenderId: '886195487754',
    projectId: 'nada-976f5',
    storageBucket: 'nada-976f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6lsF7NUqtTKXK96kGG4-dIioupA9iSUk',
    appId: '1:886195487754:ios:5b7d93a546861a89c84bf3',
    messagingSenderId: '886195487754',
    projectId: 'nada-976f5',
    storageBucket: 'nada-976f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8_pkc-hDKVBv0EJk4EZKqh6ccsCo9HO4',
    appId: '1:886195487754:web:569bb24d5a7aa768c84bf3',
    messagingSenderId: '886195487754',
    projectId: 'nada-976f5',
    authDomain: 'nada-976f5.firebaseapp.com',
    storageBucket: 'nada-976f5.firebasestorage.app',
    measurementId: 'G-DJE62PY9SR',
  );
}
